// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiLjcI5L6iRD9mzDcg7wYoyP9acraI_S8',
    appId: '1:378028871390:web:9debf30353502569d5fc4f',
    messagingSenderId: '378028871390',
    projectId: 'zootopia-ae68f',
    authDomain: 'zootopia-ae68f.firebaseapp.com',
    storageBucket: 'zootopia-ae68f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ5XS-yqETE6l_P6cS7s1u_slKTMj4KeA',
    appId: '1:378028871390:android:f5d0376f42fa1eb1d5fc4f',
    messagingSenderId: '378028871390',
    projectId: 'zootopia-ae68f',
    storageBucket: 'zootopia-ae68f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMD30PYbaDrsI4kILGLSRca6-glptoseQ',
    appId: '1:378028871390:ios:bb8fbf9a198a6e3ed5fc4f',
    messagingSenderId: '378028871390',
    projectId: 'zootopia-ae68f',
    storageBucket: 'zootopia-ae68f.firebasestorage.app',
    iosBundleId: 'com.zootopia.zootopia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMD30PYbaDrsI4kILGLSRca6-glptoseQ',
    appId: '1:378028871390:ios:bb8fbf9a198a6e3ed5fc4f',
    messagingSenderId: '378028871390',
    projectId: 'zootopia-ae68f',
    storageBucket: 'zootopia-ae68f.firebasestorage.app',
    iosBundleId: 'com.zootopia.zootopia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiLjcI5L6iRD9mzDcg7wYoyP9acraI_S8',
    appId: '1:378028871390:web:944222647df5790bd5fc4f',
    messagingSenderId: '378028871390',
    projectId: 'zootopia-ae68f',
    authDomain: 'zootopia-ae68f.firebaseapp.com',
    storageBucket: 'zootopia-ae68f.firebasestorage.app',
  );
}
